version: '2'

services:
  tss_mariadb:
    image: mariadb:10.1
    ports:
      - "3310:3306"
    volumes:
      - ./docker_data/mariadb/data:/var/lib/mysql
    container_name: tss_mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=fr
      - MYSQL_DATABASE=tss
      - MYSQL_USER=fr
      - MYSQL_PASSWORD=fr
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci